# Generated by Django 4.2.9 on 2026-01-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', 'add_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
