# Generated by Django 4.2.9 on 2026-01-25 21:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('min_quantity', models.DecimalField(decimal_places=8, default=Decimal('0.00001'), max_digits=20)),
                ('max_quantity', models.DecimalField(decimal_places=8, default=Decimal('1000000'), max_digits=20)),
                ('quantity_step', models.DecimalField(decimal_places=8, default=Decimal('0.00001'), max_digits=20)),
                ('min_price', models.DecimalField(decimal_places=8, default=Decimal('1E-8'), max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=8, default=Decimal('1000000'), max_digits=20)),
                ('price_step', models.DecimalField(decimal_places=8, default=Decimal('0.01'), max_digits=20)),
                ('min_notional', models.DecimalField(decimal_places=8, default=Decimal('10'), max_digits=20)),
                ('maker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.001'), max_digits=5)),
                ('taker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.001'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('high_24h', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('low_24h', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
            ],
            options={
                'db_table': 'trading_pairs',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop_loss', 'Stop Loss'), ('stop_limit', 'Stop Limit'), ('take_profit', 'Take Profit'), ('take_profit_limit', 'Take Profit Limit'), ('trailing_stop', 'Trailing Stop'), ('oco', 'One Cancels Other')], default='limit', max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('triggered', 'Triggered')], default='open', max_length=20)),
                ('time_in_force', models.CharField(choices=[('gtc', 'Good Till Cancelled'), ('ioc', 'Immediate or Cancel'), ('fok', 'Fill or Kill')], default='gtc', max_length=3)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('trailing_stop_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('highest_price_seen', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('lowest_price_seen', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('average_fill_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('fee_currency', models.CharField(blank=True, max_length=10)),
                ('client_order_id', models.CharField(blank=True, max_length=50)),
                ('parent_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orders', to='trading.order')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.tradingpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('buyer_fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('seller_fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('is_buyer_maker', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to=settings.AUTH_USER_MODEL)),
                ('buyer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='trading.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to=settings.AUTH_USER_MODEL)),
                ('seller_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='trading.order')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.tradingpair')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trading_pair', '-created_at'], name='trades_trading_ab734c_idx'), models.Index(fields=['buyer', '-created_at'], name='trades_buyer_i_2aead8_idx'), models.Index(fields=['seller', '-created_at'], name='trades_seller__4dbf86_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trading_pair', 'status', 'side'], name='orders_trading_cb4e25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'order_type'], name='orders_status_d97b6e_idx'),
        ),
    ]
