# Generated by Django 4.2.9 on 2026-01-22 11:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_add_stop_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tradingpair',
            options={'ordering': ['symbol']},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='trading_ord_trading_1521e9_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_user_id_17dbdf_idx',
            old_name='trading_ord_user_id_d93b91_idx',
        ),
        migrations.RenameIndex(
            model_name='trade',
            new_name='trades_trading_ab734c_idx',
            old_name='trading_tra_trading_a32f40_idx',
        ),
        migrations.RenameIndex(
            model_name='trade',
            new_name='trades_buyer_i_2aead8_idx',
            old_name='trading_tra_buyer_i_0e2b22_idx',
        ),
        migrations.RenameIndex(
            model_name='trade',
            new_name='trades_seller__4dbf86_idx',
            old_name='trading_tra_seller__450579_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tradingpair',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='filled_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='buy_order',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='buyer_is_maker',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='quote_quantity',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='sell_order',
        ),
        migrations.AddField(
            model_name='order',
            name='average_fill_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='buyer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='trading.order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_buyer_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='seller_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='trading.order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='max_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='max_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='min_notional',
            field=models.DecimalField(decimal_places=8, default=Decimal('10'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='min_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('1E-8'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='min_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00001'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='price_step',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.01'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='quantity_step',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00001'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(blank=True, default='AUTO_GENERATED', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='filled_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='highest_price_seen',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lowest_price_seen',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('triggered', 'Triggered')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='take_profit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(choices=[('gtc', 'Good Till Cancelled'), ('ioc', 'Immediate or Cancel'), ('fok', 'Fill or Kill')], default='gtc', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='trading_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.tradingpair'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trailing_stop_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyer_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trading_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.tradingpair'),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='base_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='high_24h',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='last_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='low_24h',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='maker_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.001'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='quote_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='taker_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.001'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='volume_24h',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trading_pair', 'status', 'side'], name='orders_trading_cb4e25_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'order_type'], name='orders_status_d97b6e_idx'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='trade',
            table='trades',
        ),
        migrations.AlterModelTable(
            name='tradingpair',
            table='trading_pairs',
        ),
        migrations.RemoveField(
            model_name='tradingpair',
            name='max_order_size',
        ),
        migrations.RemoveField(
            model_name='tradingpair',
            name='min_order_size',
        ),
        migrations.RemoveField(
            model_name='tradingpair',
            name='price_precision',
        ),
        migrations.RemoveField(
            model_name='tradingpair',
            name='quantity_precision',
        ),
    ]
