# Generated by Django 4.2.9 on 2026-01-26 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('chain_id', models.IntegerField(unique=True)),
                ('rpc_url', models.URLField()),
                ('explorer_url', models.URLField(blank=True, null=True)),
                ('native_currency', models.CharField(default='ETH', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_testnet', models.BooleanField(default=False)),
                ('block_time', models.IntegerField(default=12, help_text='Average block time in seconds')),
                ('confirmations_required', models.IntegerField(default=12)),
                ('last_synced_block', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
                'ordering': ['chain_id'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_addresses', to='blockchain.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitored Address',
                'verbose_name_plural': 'Monitored Addresses',
                'unique_together': {('address', 'network')},
            },
        ),
    ]
