# Generated by Django 4.2.9 on 2026-01-26 17:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency_type', models.CharField(choices=[('native', 'Native (ETH)'), ('erc20', 'ERC-20 Token'), ('internal', 'Internal Only')], default='erc20', max_length=20)),
                ('contract_address', models.CharField(blank=True, help_text='ERC-20 contract address (null for native ETH)', max_length=42, null=True)),
                ('decimals', models.IntegerField(default=18)),
                ('chain_id', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deposit_enabled', models.BooleanField(default=True)),
                ('is_withdrawal_enabled', models.BooleanField(default=True)),
                ('min_deposit', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('min_withdrawal', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('withdrawal_fee', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('fee', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=36)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('chain_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallets.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('trade_buy', 'Trade Buy'), ('trade_sell', 'Trade Sell'), ('fee', 'Trading Fee'), ('order_lock', 'Order Lock'), ('order_unlock', 'Order Unlock'), ('admin_credit', 'Admin Credit'), ('admin_debit', 'Admin Debit')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=18, help_text='Positive for credit, negative for debit', max_digits=36)),
                ('balance_before', models.DecimalField(decimal_places=18, max_digits=36)),
                ('balance_after', models.DecimalField(decimal_places=18, max_digits=36)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallets.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'currency'], name='wallets_led_user_id_345d8e_idx'), models.Index(fields=['reference_type', 'reference_id'], name='wallets_led_referen_2f17c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(db_index=True, max_length=66)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=12)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirming', 'Confirming'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('chain_id', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallets.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
                'unique_together': {('tx_hash', 'chain_id')},
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.DecimalField(decimal_places=18, default=Decimal('0'), help_text='Available for trading/withdrawal', max_digits=36, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('locked', models.DecimalField(decimal_places=18, default=Decimal('0'), help_text='Locked in open orders', max_digits=36, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='wallets.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'ordering': ['currency__symbol'],
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
