# Generated by Django 4.2.9 on 2026-01-26 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBalanceAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('balance_before', models.DecimalField(decimal_places=18, max_digits=36)),
                ('balance_after', models.DecimalField(decimal_places=18, max_digits=36)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.currency')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.ledgerentry')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Balance Adjustment',
                'verbose_name_plural': 'Admin Balance Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('wallet_connect', 'Wallet Connect'), ('wallet_disconnect', 'Wallet Disconnect'), ('wallet_verify', 'Wallet Verify'), ('order_create', 'Order Create'), ('order_cancel', 'Order Cancel'), ('trade_execute', 'Trade Execute'), ('deposit_create', 'Deposit Create'), ('deposit_credit', 'Deposit Credit'), ('withdrawal_request', 'Withdrawal Request'), ('withdrawal_approve', 'Withdrawal Approve'), ('withdrawal_reject', 'Withdrawal Reject'), ('withdrawal_process', 'Withdrawal Process'), ('admin_balance_adjust', 'Admin Balance Adjust'), ('admin_user_update', 'Admin User Update'), ('admin_settings_change', 'Admin Settings Change'), ('api_access', 'API Access'), ('error', 'Error')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx')],
            },
        ),
    ]
