# Generated by Django 4.2.9 on 2026-01-25 18:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='kyclevel',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='kycprofile',
            options={'verbose_name': 'KYC Profile', 'verbose_name_plural': 'KYC Profiles'},
        ),
        migrations.RenameField(
            model_name='kycdocument',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='kyclevel',
            old_name='requires_id_document',
            new_name='can_deposit_fiat',
        ),
        migrations.RenameField(
            model_name='kycprofile',
            old_name='address_verified_at',
            new_name='verified_at',
        ),
        migrations.RenameField(
            model_name='kycverificationrequest',
            old_name='additional_info_request',
            new_name='review_notes',
        ),
        migrations.RemoveField(
            model_name='kycauditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kycauditlog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='kycauditlog',
            name='old_value',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='extracted_data',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='issuing_country',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='kyclevel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kyclevel',
            name='requires_email',
        ),
        migrations.RemoveField(
            model_name='kyclevel',
            name='requires_phone',
        ),
        migrations.RemoveField(
            model_name='kyclevel',
            name='requires_proof_of_address',
        ),
        migrations.RemoveField(
            model_name='kyclevel',
            name='requires_selfie',
        ),
        migrations.RemoveField(
            model_name='kyclevel',
            name='requires_source_of_funds',
        ),
        migrations.RemoveField(
            model_name='kyclevel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='identity_verified_at',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='is_pep',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='is_sanctioned',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='phone_verified_at',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='kycverificationrequest',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='kycverificationrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='kycverificationrequest',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='kycverificationrequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='kycverificationrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='kycverificationrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='kycauditlog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='kyclevel',
            name='required_documents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='id_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='risk_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='tax_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycverificationrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kycauditlog',
            name='action',
            field=models.CharField(choices=[('profile_created', 'Profile Created'), ('profile_updated', 'Profile Updated'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('verification_submitted', 'Verification Submitted'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('level_upgraded', 'Level Upgraded'), ('level_downgraded', 'Level Downgraded'), ('profile_suspended', 'Profile Suspended')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kycauditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID (Aadhaar/PAN)'), ('drivers_license', "Driver's License"), ('selfie', 'Selfie with ID'), ('proof_of_address', 'Proof of Address'), ('bank_statement', 'Bank Statement'), ('utility_bill', 'Utility Bill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='file',
            field=models.FileField(upload_to='kyc_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='kyclevel',
            name='can_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kyclevel',
            name='daily_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kyclevel',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kyclevel',
            name='level',
            field=models.IntegerField(choices=[(0, 'Unverified'), (1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced')], unique=True),
        ),
        migrations.AlterField(
            model_name='kyclevel',
            name='monthly_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kyc.kyclevel'),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverificationrequest',
            name='request_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverificationrequest',
            name='target_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='kyc.kyclevel'),
        ),
        migrations.AlterModelTable(
            name='kycauditlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kycdocument',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kyclevel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kycprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kycverificationrequest',
            table=None,
        ),
    ]
